name: Bot-Test-Build

on:
  push:
    paths-ignore: 
      -'**/*.md'
jobs: 
  OnPush:
    runs-on: ubuntu-latest
    env: 
      DOTNET_CORE_VERSION: 6.0.X
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: TRUE
      BUILD_CONFIG: Release
      BOT_PATH: 'BotPeliculas.Bot'
      TESTS_PATH: 'BotPeliculas.Tests'
    steps: 
      - name: Checkout ('${{ github.repository }}' cloned)
        uses: actions/checkout@v2

      - name: Setup DotNet Core (${{env.DOTNET_CORE_VERSION}})
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          
      - name: Restore Packages
        run: dotnet restore ${{env.BOT_PATH}}

      - name: build
        run: dotnet build --configuration ${{env.BUILD_CONFIG}}
        working-directory: "${{env.BOT_PATH}}"

      - name: test
        run: dotnet test ${{env.TESTS_PATH}}
