name: BuildAndTes
on:
  push:
    paths-ignore: 
      -'**/*.md'
jobs: 
  OnPush:
    runs-on: ubuntu-latest
    env: 
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: TRUE
    steps: 
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup DotNet Core 6.0
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0'
          
      - name: Build with dotnet
        run: dotnet build BotPeliculas.Bot/BotPeliculas.sln --configuration Release
        
      - name: Test
        run: dotnet test BotPeliculas.Tests/BotPeliculas.Tests.csproj
