name: Build and deploy ASP.Net Core app to Azure Web App - botpelispw3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build BotPeliculas.Bot/BotPeliculas.sln --configuration Release

      - name: Publish
        run: dotnet publish BotPeliculas.Bot/BotPeliculas.sln --configuration Release --output ${{github.workspace}}/BotBuild

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BotBuild
          path: ${{github.workspace}}/BotBuild

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: BotBuild
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A3E548C35C641CEAF901700F8FC9BDF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F4FC2D0A1404963AC1C99BA4C70AD1D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64A1B0214FF640AD8F25106F09EFC880 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'botpelispw3'
          slot-name: 'Production'
          package: .
          
