name: Bot-Test-Build
on:
  push:
    paths-ignore: 
      - '**/*.md'
jobs: 
  OnPush:
    runs-on: ubuntu-latest
    env: 
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
      DOTNET_NOLOGO: TRUE
      BUILD_CONFIG: Release
      BOT_PATH: 'BotPeliculas.Bot/BotPeliculas.Bot.csproj'
      TESTS_PATH: 'BotPeliculas.Tests/BotPeliculas.Tests.csproj'
      AZURE_WEBAPP_NAME: 'BotPeliculasPw3'
      AZURE_RESOURCE_GROUP: 'BotPeliculasPw3 '
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0'
          
      - name: Restore Packages
        run: dotnet restore ${{ env.BOT_PATH }}
      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIG }} ${{ env.BOT_PATH }}

      - name: Test
        run: dotnet test ${{ env.TESTS_PATH }}
